name: Release app

on:
  push:
    tags:        # Remove the `branches` node and add this one
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test -B


  deliver-jar:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build the JAR file with Maven
        run: mvn package -B
      - name: Upload the JAR file to GitHub as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-project-jar-file
          path: target/*.jar

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: deliver-jar  # doğru job’a referans veriyoruz
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: zipped-project-jar-file  # doğru artifact ismi
          path: build
      - run: zip -r build.zip build/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build.zip
