name: Maven test
on: push




jobs:
  deliver-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn compile
      - run: mvn test
      - run: mvn package
      - uses: actions/upload-artifact@v4
        with:
          name: zipped-project-jar-file
          path: target/*.jar


  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: deliver-jar
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zipped-project-jar-file
          path: build
      - name: zip artifact
        run: zip -r build.zip build/
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifact: build.zip